```
 NIP: 7
 Title: Proposal for setting a max supply limit to NULS
 Author: Berzeck <Berzeck@nulstar.com>
 Discussions-To: [https://nuls.community/d/531-ncg20190617-max-supply-deflation-method/13](https://forum.nuls.io/t/nip-7-proposal-for-setting-a-max-supply-limit-to-nuls/67)
 Status: Accepted
 Type: Core
 Created: 2019-06-17

```

## 1] Preamble

Currently NULS does not have a fixed maximum limit of coins as 5000000 are created each year specifically to reward agents and stakers. This is not sustainable long-term because it can be proved that if max supply tends to infinity price tends to zero, this is not  a matter of opinion but a mathematical certainty, inflation can grow for several years as it is assumed that new people will enter the market and will continue sustaining current and higher price levels, that�s the case of Ethereum for example, but even then, the number of persons and the amount of money is finite so at some point the sell pressure will undoubtedly be unsustainable and price will start crunching.

#### The proposal was accepted after 2 weeks of community voting.

## 2] Abstract

Te maxium supply was set at 210 000 000 NULS, the method to be implemented is a smooth non disruptive curve that will decrease the number of rewards per month by a small percentage, this percentage changes a little in the last blocks in order to reach the 210 000 000 NULS goal exactly.

## 3] Motivation

#### 3.1] Avoid price crunch  
It is important to provide a very slow and smooth reward decrease function until rewards are generated only by transaction, contract and dapp fees. This can take many decades if needed and can be reviewed every year if community considers it appropriate.


#### 3.2] Reward early partners and investors
Having a max supply tends to increase buying pressure long term due economics of scarcity, the more the circulating supply approaches the theoretical limit then the greater probability that buying pressure will increase, this property rewards early partners and long-term investors more than late comers and traders, as it should be, because early investors take more risk than those that come when the project is mature.

#### 3.3] Increase probability to break strong resistance price levels
Let�s put an example. Assume price in the bull market increases to 30 USD per NULS, it is reasonable to think that agents and stakers dump at least 40% of their gains (average) ; it is also easy to calculate the daily reward amount: R = 5 000 000 / 365 = 13 698, 40% of that is 5479 Nuls being dumped per day (average) which is equivalent to 164 370 USD per day (average) just to sustain the 30 $us level! Decreasing rewards smoothly implies that the amount of USD required to sustain 30$us will be lower next market cycle .

## 4] Specification

#### 4.1] Starting on 12th July 2020 , rewards should be decreased exactly 0.4%.

#### 4.2] After step 1] is completed, the step is repeated every 30 days, which implies decreasing rewards another 0.4% per month on average.

#### 4.3] Repeat the process until the 210 000 000 NULS goal is met. 

## 5] Rationale

The method to be implemented starts decreasing rewards on 12th July 2020, two years after main net was activated, and have a Max Cap of exactly 210 000 000 NULS that will be reached after 78 years from activation.
NULS price will need to rise less than 5% per year to offer the same value proposition to agents and stakers.

It will need 14 years for the rewards to be halved, it�s easy to assume that we will more than duplicate the price and amount of investors in such long timeframe!

After analyzing many  alternatives on how to reach the max cap, this, in my opinion,  is by far the best method for several reasons:

#### 5.1] It is very easy to implement: this method requires very few changes in code so it will make the upgrade more secure, something very important as  changing the blockchain protocol is a very delicate process.

#### 5.2] It is very efficient: Most other methods are cumbersome and add unnecessary strain on the network. The method chosen needs to be as efficient as possible or we will hinder scalability prospects of the network.  

#### 5.3] It is non disruptive: The function is very smooth so it should not have negative impact on stakers, halving (the method used for Bitcoin) is very disruptive but in case of PoW coins, miners need to continue mining and there are very few coins aside from Bitcoin that are worth mining so they are stuck with Bitcoin, in case of PoS this is not the case so stakers can easily switch to other coin if the rewards decrease too much and never come back, this is why it is strongly recommended not to use halving as the chosen method.


## Backwards Compatibility

* Backward incompatibility

Rrewards represent a core feature in consensus so old nodes won't accept new blocks generated by nodes that updated the protocol, thit will lead to a hard fork.

We can take advantage of te fact that NULS 2.0 is updating the protocol to reduce the risk to its minimum level.
