```
  NIP: 3
  Title: Community Fund Management and Use of Process
  Author: Reaper Ran <reaper@nuls.io>
  Discussions-To: https://forum.nuls.io/t/nip-3-community-fund-management-and-use-of-process/60
  Status: Last call
  Type: Process
  Created: 2018-12-28
```





## Abstract

According to the needs of the ecological development of the NULS community, the management and use of the NULS community fund is based on the principles of fairness, justice and openness. The NULS Community Fund account is open to the community and is monitored by community members. All incentive proposals are managed according to the community Charter and can be used to cover expenses. The funds in the account are managed by the NULS governance platform and the multi-signatures of NULS Councilors.



## Motivation

In order to enable the community to have more talents to join, community funds are opened to the community for joint management and use.



## Specification

The following is a specification of the Community Fund Management and Use of Process.



# Community Fund Management and Use of Process


## **I. Community Fund Management**

According to the needs of the ecological development of the NULS community, the management and use of the NULS community fund is based on the principles of fairness, justice and openness. The NULS Community Fund account is open to the community and is monitored by community members. All incentive proposals are managed according to the community Charter and can be used to cover expenses. The funds in the account are managed by the NULS governance platform and the multi-signatures of NULS Councilors.

Community Fund Account Address:

https://gov.nuls.io/gov/


Councilors are elected by community votes and are responsible for managing proposals initiated by community contributors and their execution.

Councilors list: https://gov.nuls.io/gov/


## **II. The Application Member**

All NULS contributors, NULS Holders, community volunteers, and any other members who want to participate in the NULS community contributions. The community vote for the proposal is held for 15 days.


## **III. The Type of Application**

### **1. Proposal to Pay Funds**

The applicant has already done something and needs to pay for some of the costs incurred by the matter. This payment applies to a one-time payment or a specific transaction. Based on NULS, a single application does not exceed 10,000 NULS.

### **2. Proposal Budget Item**

The applicant has a plan to execute and needs to initiate a proposal for a budgeted project. Proposal budget item is applicable to specific contributor roles or community members to participate in the contribution. After the proposal is passed, periodic payment will be made in installments. For example, community management, platform information maintenance, etc. The budget project is based on NULS and the maximum single-budget application does not exceed 20,000 NULS.

### **3. The Proposal to Create a Node**

Applicants can apply for a proposal to create a node through a community fund. The creation node can specify and obtain the reward address, and the funds that create the node and/or deposit requirement are still owned by the community fund. This approach is suitable for long-term cooperation such as NTC members, other capable teams, developers, or operational partners. Creation of a node deposit is equal to 20,000 NULS.  

**4. Proposal Entrusted Funds**

Applicants can apply for NULS to be entrusted to a node through a community fund. It can be a node created by the proposal, or a node created by the applicant itself. The entrusted NULS and the consensus rewards generated by the commission are owned by the community fund. This approach can be combined with a proposal creation node and is suitable for long-term cooperation to include Ambassadors,  members, other capable teams, developers, or operational partners, etc. The maximum amount of funds requested for application is 500,000 NULS.

## **IV. The Application Process**

### **1. The Plan is Openly and Thoroughly Discussed**

(1) Display the plan, program or proposal in the community forum and openly discuss and answer the questions raised by the community;

(2) Make the plan or revisions to the plan more complete according to the suggestions made by the community, to include the use of the funding for the program which needs to be clear, forthright, transparent and fully understood by the whole community;

(3) The methods that can be applied for in the scheme include payment of funds, budget items, creation of nodes, and entrusted funds;

(4) The proposal to pay the funds necessitates clarification of the amount of funds, the purpose for the funds, and the effective evaluation and clear projections of the results to be obtained;

(5) Proposal budget items require detailed plans, funding amounts, uses, payment cycles and performance estimates;

(6) For proposal to create a node, you need to specify the address of the reward, the purpose of creating the node, quantify and present the reward calculation generated by the node, and include the future plan of the applicant or the partner;

(7) The entrusted funds of the proposal need to clarify the address of the award, the purpose of the entrustment, the calculation of the amount generated by the entrustment, and the future plan of the applicant or the partner;

(8) All proposals initiated by the community are fully discussed (for no less than 7 days) and are fully understood by all community members and submitted to the Councilors for formal proposals;

### **2. Councilor Proposal**

(1) Councilors receive community-sponsored proposals that have been fully discussed, and then need to assign an NCG number (NCG + date + Item Number 01, 02 ) and make a formal proposal and initiate a community vote;

(2) Both the council and the applicant need to guide the community to vote correctly in the best interest of NULS ecosystem;

(3) After the completion of the voting, if the support rate of the community charter is greater than or equal to the proposal it passes, and if lower than the proposal support rate the vote is considered invalid, and needs to be revised, and re-submitted according to the entire process;

(4) The members of the Council submit applications for funds to the Foundation. The proposal application needs to provide a link for discussion, a link to vote, and an NCG number. The foundation must implement the proposal adopted by the community if the fund has no security risks or other immediate insurmountable obstacles.

### **3. Foundation Implementation Proposal**

(1) If the Foundation receives an application for a proposal submitted by a member of the Council, it will take 3 working days to carry out the relevant operations;

(2) In the processed transaction note, you need to fill in the NCG number of each transaction. If it is a multi-period or installment payment budget item, you need to add the period or payment installment number.  (NCG+date+item+period/installment number such as 01 or 04). 

## **V. Process Explanation**

All community discussion suggestions are made at https://forum.nuls.io/

This process is managed according to the community's charter ideas, and the process will be open to entirety of all and any NULS global communities.

Updates to process rules can also be presented as a proposal, in accordance with the Community Charter and NIP.

The specific node generates revenue with reference to the NULS POC consensus mechanism.

###

 
